version: '3.3'

services:
  food-catalog:
    container_name: food-catalog
    image: basharlabadi/nutracker-food-catalog:${FOOD_CATALOG_TAG}
    ports:
      - "8001:8001"
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
  entries:
    container_name: entries
    image: basharlabadi/nutracker-entries:${ENTRIES_TAG}
    ports:
      - "8003:8003"
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
  identity:
    container_name: identity
    image: basharlabadi/nutracker-identity:${IDENTITY_TAG}
    ports:
      - "8002:8002"
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
#  gateway:
#    container_name: gateway
#    image: basharlabadi/nutracker-gateway:${GATEWAY_TAG}
#    ports:
#      - "8080:8080"
#    environment:
#      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}

