---
# this config is for the config server app
# by default the local dev profile is active can be overridden with inline args
spring:
  profiles:
    # this has to be the word native to run locally, you can't choose another name like dev, local
    active: native
  application:
    name: configserver-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blabadi/nutracker-configserver
          searchPaths: configserver-data
        native:
          # if we want to have the properties outside the classpath to avoid rebuilding we can use file system to
          # through this property key
          searchLocations: ${NUTRACKER_LOCAL_CONFIG_URL:classpath:local-config}
server:
  port: 8888



