#TODO: check how to scale eurka server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  devtools:
    remote:
      secret: thisismysecret
